name: farmers_journal
description: "farmers jounal app project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.6+1
environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.14
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  table_calendar: ^3.1.2
  intl: any
  fl_chart: ^0.69.0
  google_maps_flutter: ^2.10.0
  flutter_dotenv: ^5.2.1
  go_router: ^14.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  firebase_auth: ^5.3.4
  firebase_ui_auth: ^1.16.0
  freezed_annotation: ^2.4.4
  kakao_flutter_sdk_user: ^1.9.5
  json_annotation: ^4.9.0
  sign_in_with_apple: ^6.1.4
  excel: ^4.0.6
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  dart_firebase_admin: ^0.4.0
  flutter_svg_provider: ^1.0.7
  shared_preferences: ^2.5.2
  photo_manager: ^3.6.4
  font_awesome_flutter: ^10.8.0



dev_dependencies:
  json_serializable: ^6.9.2
  freezed: ^2.5.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/app_icon_splash_1.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/app_icon_splash_1.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Pretandard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Thin.otf

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/avatars/
    - assets/svgs/
    - assets/fonts/
    - .env