// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5P2-tLO2SLWISirBZelZtjaNLk_23og',
    appId: '1:80482822005:web:57304010c466e6f039953c',
    messagingSenderId: '80482822005',
    projectId: 'farmers-journal-7f2cc',
    authDomain: 'farmers-journal-7f2cc.firebaseapp.com',
    storageBucket: 'farmers-journal-7f2cc.appspot.com',
    measurementId: 'G-M04D2YG7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfk4vCB-iSzaeJM85DoeZ9LqLA7dkEc-s',
    appId: '1:80482822005:android:0c6c03c68ef7061b39953c',
    messagingSenderId: '80482822005',
    projectId: 'farmers-journal-7f2cc',
    storageBucket: 'farmers-journal-7f2cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA847Y-rI2TprKxVAUrNJkrsx2bf0KEvOY',
    appId: '1:80482822005:ios:fb616b63ab3c76a039953c',
    messagingSenderId: '80482822005',
    projectId: 'farmers-journal-7f2cc',
    storageBucket: 'farmers-journal-7f2cc.appspot.com',
    iosBundleId: 'com.yesj1234.farmersJournal',
  );

}