import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../../domain/model/real_time_auction_info.dart';
import 'auction_price_controller_state.dart';

part 'auction_price_controller.g.dart';

@riverpod
class AuctionPriceController extends _$AuctionPriceController {
  List<AuctionPrice> get dummyData => [
        AuctionPrice(
          saledate: '20240501',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1200',
          qty: '500',
          std: '1kg',
          sbidtime: '202405010600',
        ),
        AuctionPrice(
          saledate: '20240502',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1350',
          qty: '450',
          std: '1kg',
          sbidtime: '202405020600',
        ),
        AuctionPrice(
          saledate: '20240503',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1100',
          qty: '600',
          std: '1kg',
          sbidtime: '202405030600',
        ),
        AuctionPrice(
          saledate: '20240504',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1250',
          qty: '520',
          std: '1kg',
          sbidtime: '202405040600',
        ),
        AuctionPrice(
          saledate: '20240505',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1400',
          qty: '490',
          std: '1kg',
          sbidtime: '202405050600',
        ),
        AuctionPrice(
          saledate: '20240506',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1300',
          qty: '510',
          std: '1kg',
          sbidtime: '202405060600',
        ),
        AuctionPrice(
          saledate: '20240507',
          whsalcd: '110001',
          whsalname: '서울가락시장',
          cmpcd: '11000105',
          cmpname: '서울청과',
          large: '13',
          largename: '채소류',
          mid: '26',
          midname: '근채류',
          small: '03',
          smallname: '무',
          sancd: '001',
          sanname: '제주',
          cost: '1450',
          qty: '530',
          std: '1kg',
          sbidtime: '202405070600',
        ),
      ];

  @override
  AuctionPriceControllerState build() {
    final List<AuctionPrice> data = dummyData;
    data.sort((a, b) => a.saledate.compareTo(b.saledate)); // 날짜순 정렬
    return AuctionPriceControllerState.data(data);
  }
}
